title: Pranav CSP
description: "Pranav's CS Portfolio"
owner_name: Pranav Santhosh
github_username: SanPranav
github_repo: "Pranav_2025" 
baseurl: "/Pranav_2025"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/SanPranav"}
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
- none 